services:
  db:
    image: postgres:16
    container_name: event-manager-db
    environment:
      POSTGRES_USER: event_manager
      POSTGRES_PASSWORD: event_manager
      POSTGRES_DB: event_manager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: